import ChartPie from './pie.vue'
import ChartBar from './bar.vue'
import TypePie from './typePie.vue'
import TypeBar from './typeBar.vue'
import KindPie from './kindPie.vue'
import KindBar from './kindBar.vue'
import WaterPolo from './waterPolo.vue'
import TipsPie from './tipsPie.vue'
import TipsBar from './tipsBar.vue'
import CrossBar from './crossBar.vue'
export { ChartPie, ChartBar,TypePie,TypeBar, KindPie, KindBar,WaterPolo,TipsPie,TipsBar,CrossBar }