module.exports = {
  pc: [
    {
      key: "pc2_city_one",
      title: "省市级平台-侧边栏简易暗黑风格",
      layout: "pc2",
      thema: "dark",
      imgurl: "/static/imgstest/1.png",
      menu: "pc2",
    },
    {
      key: "pc2_city_two",
      title: "省市级平台-侧边栏简易明亮风格",
      layout: "pc2",
      thema: "light",
      imgurl: "/static/imgstest/3.png",
      menu: "pc2",
    },
    {
      key: "top_one",
      title: "省市级平台-顶部简易暗黑风格",
      layout: "top",
      thema: "dark",
      imgurl: "/static/imgstest/2.png",
      menu: "top",
      headline: "机动车环保检验管理平台",
    },
    {
      key: "top_two",
      title: "省市级平台-顶部简易明亮风格",
      layout: "top",
      thema: "light",
      imgurl: "/static/imgstest/4.png",
      menu: "top",
      headline: "机动车环保检验管理平台统",
    },
  ],
  phone: [
    {
      title: "明亮紫风格",
      layout: "pad",
      thema: "light_purple",
      imgurl: "/static/imgstest/15.png",
      menu: "pad",
    },
    {
      title: "明亮蓝风格",
      layout: "pad",
      thema: "light_blue",
      imgurl: "/static/imgstest/16.png",
      menu: "pad",
    },
    {
      title: "暗黑经典风格",
      layout: "pad",
      thema: "dark",
      imgurl: "/static/imgstest/17.png",
      menu: "pad",
    },
  ],
};
